# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: transport/internet/grpc/encoding/stream.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import xray_api.proto.transport.internet.grpc.encoding.stream_pb2


class GRPCServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Tun(self, stream: 'grpclib.server.Stream[transport.internet.grpc.encoding.stream_pb2.Hunk, transport.internet.grpc.encoding.stream_pb2.Hunk]') -> None:
        pass

    @abc.abstractmethod
    async def TunMulti(self, stream: 'grpclib.server.Stream[transport.internet.grpc.encoding.stream_pb2.MultiHunk, transport.internet.grpc.encoding.stream_pb2.MultiHunk]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/xray.transport.internet.grpc.encoding.GRPCService/Tun': grpclib.const.Handler(
                self.Tun,
                grpclib.const.Cardinality.STREAM_STREAM,
                xray_api.proto.transport.internet.grpc.encoding.stream_pb2.Hunk,
                xray_api.proto.transport.internet.grpc.encoding.stream_pb2.Hunk,
            ),
            '/xray.transport.internet.grpc.encoding.GRPCService/TunMulti': grpclib.const.Handler(
                self.TunMulti,
                grpclib.const.Cardinality.STREAM_STREAM,
                xray_api.proto.transport.internet.grpc.encoding.stream_pb2.MultiHunk,
                xray_api.proto.transport.internet.grpc.encoding.stream_pb2.MultiHunk,
            ),
        }


class GRPCServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Tun = grpclib.client.StreamStreamMethod(
            channel,
            '/xray.transport.internet.grpc.encoding.GRPCService/Tun',
            xray_api.proto.transport.internet.grpc.encoding.stream_pb2.Hunk,
            xray_api.proto.transport.internet.grpc.encoding.stream_pb2.Hunk,
        )
        self.TunMulti = grpclib.client.StreamStreamMethod(
            channel,
            '/xray.transport.internet.grpc.encoding.GRPCService/TunMulti',
            xray_api.proto.transport.internet.grpc.encoding.stream_pb2.MultiHunk,
            xray_api.proto.transport.internet.grpc.encoding.stream_pb2.MultiHunk,
        )
