# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: app/stats/command/command.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import xray_api.proto.app.stats.command.command_pb2


class StatsServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetStats(self, stream: 'grpclib.server.Stream[app.stats.command.command_pb2.GetStatsRequest, app.stats.command.command_pb2.GetStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def QueryStats(self, stream: 'grpclib.server.Stream[app.stats.command.command_pb2.QueryStatsRequest, app.stats.command.command_pb2.QueryStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetSysStats(self, stream: 'grpclib.server.Stream[app.stats.command.command_pb2.SysStatsRequest, app.stats.command.command_pb2.SysStatsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/xray.app.stats.command.StatsService/GetStats': grpclib.const.Handler(
                self.GetStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                xray_api.proto.app.stats.command.command_pb2.GetStatsRequest,
                xray_api.proto.app.stats.command.command_pb2.GetStatsResponse,
            ),
            '/xray.app.stats.command.StatsService/QueryStats': grpclib.const.Handler(
                self.QueryStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                xray_api.proto.app.stats.command.command_pb2.QueryStatsRequest,
                xray_api.proto.app.stats.command.command_pb2.QueryStatsResponse,
            ),
            '/xray.app.stats.command.StatsService/GetSysStats': grpclib.const.Handler(
                self.GetSysStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                xray_api.proto.app.stats.command.command_pb2.SysStatsRequest,
                xray_api.proto.app.stats.command.command_pb2.SysStatsResponse,
            ),
        }


class StatsServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.stats.command.StatsService/GetStats',
            xray_api.proto.app.stats.command.command_pb2.GetStatsRequest,
            xray_api.proto.app.stats.command.command_pb2.GetStatsResponse,
        )
        self.QueryStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.stats.command.StatsService/QueryStats',
            xray_api.proto.app.stats.command.command_pb2.QueryStatsRequest,
            xray_api.proto.app.stats.command.command_pb2.QueryStatsResponse,
        )
        self.GetSysStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.stats.command.StatsService/GetSysStats',
            xray_api.proto.app.stats.command.command_pb2.SysStatsRequest,
            xray_api.proto.app.stats.command.command_pb2.SysStatsResponse,
        )
