"""feat: add sub_revoked_at

Revision ID: 0e66648e57ba
Revises: fd423c19f682
Create Date: 2024-10-06 12:17:05.256271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e66648e57ba'
down_revision = 'fd423c19f682'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("sub_revoked_at", sa.DateTime(), nullable=True, server_default=None),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sub_revoked_at")
    # ### end Alembic commands ###
