"""add sub_revoked_at to users table

Revision ID: 1992c49c5990
Revises: fd423c19f682
Create Date: 2024-10-09 05:24:52.450988

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1992c49c5990"
down_revision = "fd423c19f682"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("sub_revoked_at", sa.DateTime()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sub_revoked_at")
    # ### end Alembic commands ###
