"""add allowed_ips to hosts

Revision ID: be0032100c07
Revises: c97bd32e6e12
Create Date: 2024-11-11 08:27:05.882157

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be0032100c07"
down_revision = "c97bd32e6e12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hosts",
        sa.Column("allowed_ips", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "allowed_ips")
    # ### end Alembic commands ###
