"""service users limit

Revision ID: 395fd121d136
Revises: a015ed8ce227
Create Date: 2024-12-07 04:13:12.651532

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "395fd121d136"
down_revision = "a015ed8ce227"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services", sa.Column("users_limit", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "users_limit")
    # ### end Alembic commands ###
