"""hold user last reset and lifetime_used_traffic inside the table

Revision ID: 058eb11c5b17
Revises: 74e234a3bd4b
Create Date: 2024-05-26 21:16:06.762089

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "058eb11c5b17"
down_revision = "74e234a3bd4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_usage_logs")
    op.add_column(
        "users",
        sa.Column(
            "lifetime_used_traffic",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "traffic_reset_at",
            sa.DateTime(),
            server_default=sa.sql.null(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "traffic_reset_at")
    op.drop_column("users", "lifetime_used_traffic")
    op.create_table(
        "user_usage_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("used_traffic_at_reset", sa.BIGINT(), nullable=False),
        sa.Column("reset_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
