"""unbound host

Revision ID: 57eba0a293f2
Revises: 982867b533e6
Create Date: 2024-12-18 20:22:11.860923

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57eba0a293f2"
down_revision = "982867b533e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hosts_services",
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("host_id", "service_id"),
    )
    op.add_column(
        "hosts",
        sa.Column("host_protocol", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "hosts", sa.Column("host_network", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "hosts", sa.Column("uuid", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "hosts", sa.Column("password", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "hosts", sa.Column("header_type", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "hosts",
        sa.Column("reality_public_key", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "hosts", sa.Column("reality_short_ids", sa.JSON(), nullable=True)
    )
    op.add_column(
        "hosts", sa.Column("flow", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "hosts", sa.Column("shadowtls_version", sa.Integer(), nullable=True)
    )
    op.add_column(
        "hosts",
        sa.Column("shadowsocks_method", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "hosts", sa.Column("splithttp_settings", sa.JSON(), nullable=True)
    )
    op.add_column(
        "hosts",
        sa.Column(
            "universal",
            sa.Boolean(),
            server_default=sa.sql.false(),
            nullable=False,
        ),
    )
    op.alter_column(
        "hosts", "inbound_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "universal")
    op.drop_column("hosts", "splithttp_settings")
    op.drop_column("hosts", "shadowsocks_method")
    op.drop_column("hosts", "shadowtls_version")
    op.drop_column("hosts", "flow")
    op.drop_column("hosts", "reality_short_ids")
    op.drop_column("hosts", "reality_public_key")
    op.drop_column("hosts", "header_type")
    op.drop_column("hosts", "password")
    op.drop_column("hosts", "uuid")
    op.drop_column("hosts", "host_network")
    op.drop_column("hosts", "host_protocol")
    op.drop_table("hosts_services")
    op.alter_column(
        "hosts", "inbound_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
