"""add removed to users for soft delete

Revision ID: b0357faf51c8
Revises: 3acfdeb79b78
Create Date: 2024-07-14 19:58:54.430547

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b0357faf51c8"
down_revision = "3acfdeb79b78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "removed",
            sa.Boolean(),
            server_default=sa.sql.false(),
            nullable=False,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "removed")
    # ### end Alembic commands ###
