"""add removed-at

Revision ID: 2524f7ac2676
Revises: 57eba0a293f2
Create Date: 2025-10-07 01:16:41.156593

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2524f7ac2676"
down_revision = "57eba0a293f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("removed_at", sa.DateTime(), nullable=True)
    )
    op.execute(
        "UPDATE users SET removed_at = NOW() AT TIME ZONE 'UTC' WHERE is_removed = TRUE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "removed_at")
    # ### end Alembic commands ###
