"""add removed-at

Revision ID: 2524f7ac2676
Revises: 57eba0a293f2
Create Date: 2025-10-07 01:16:41.156593

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "2524f7ac2676"
down_revision = "57eba0a293f2"
branch_labels = None
depends_on = None


def get_database_type():
    bind = op.get_bind()
    return bind.dialect.name


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("removed_at", sa.Date(), nullable=True))

    db_type = get_database_type()

    if db_type == "postgresql":
        op.execute(
            "UPDATE users SET removed_at = (CURRENT_DATE AT TIME ZONE 'UTC')::date WHERE removed = TRUE"
        )
    elif db_type == "sqlite":
        op.execute(
            "UPDATE users SET removed_at = date('now') WHERE removed = TRUE"
        )
    elif db_type in ["mysql", "mariadb"]:
        op.execute(
            "UPDATE users SET removed_at = UTC_DATE() WHERE removed = TRUE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "removed_at")
    # ### end Alembic commands ###
