"""Add 2FA fields to admins table

Revision ID: 18a18f6c0be3
Revises: 57eba0a293f2
Create Date: 2025-07-27 13:54:01.987449

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18a18f6c0be3"
down_revision = "57eba0a293f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins", sa.Column("otp_secret", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "admins",
        sa.Column(
            "is_otp_enabled",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "is_otp_enabled")
    op.drop_column("admins", "otp_secret")
    # ### end Alembic commands ###
