"""make host alpn string

Revision ID: 5410d8ec78ff
Revises: b0357faf51c8
Create Date: 2024-07-24 22:47:51.528849

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql, mysql

# revision identifiers, used by Alembic.
revision = "5410d8ec78ff"
down_revision = "b0357faf51c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if (dialect := op.get_bind().dialect.name) == "postgresql":
        op.alter_column(
            "hosts",
            "alpn",
            existing_type=postgresql.ENUM(
                "none", "h2", "http/1.1", "h2,http/1.1", name="proxyhostalpn"
            ),
            type_=sa.String(length=32),
            existing_nullable=False,
            nullable=True,
            server_default=None,
        )
    elif dialect == "mysql" or dialect == "mariadb":
        op.alter_column(
            "hosts",
            "alpn",
            existing_type=mysql.ENUM("none", "h2", "http/1.1", "h2,http/1.1"),
            type_=sa.String(length=32),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if (dialect := op.get_bind().dialect.name) == "postgresql":
        op.alter_column(
            "hosts",
            "alpn",
            existing_type=sa.String(length=32),
            type_=postgresql.ENUM(
                "none", "h2", "http/1.1", "h2,http/1.1", name="proxyhostalpn"
            ),
            existing_nullable=True,
            nullable=False,
            existing_server_default=None,
            server_default=sa.text("'none'::proxyhostalpn"),
        )
    elif dialect == "mysql" or dialect == "mariadb":
        op.alter_column(
            "hosts",
            "alpn",
            existing_type=sa.String(length=32),
            type_=mysql.ENUM("none", "h2", "http/1.1", "h2,http/1.1"),
            nullable=False,
            existing_server_default=None,
            server_default=sa.text("'none'"),
        )
    # ### end Alembic commands ###
