# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05mnode\"\"\n\x10XrayStartRequest\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"\x86\x01\n\x11XrayStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x0f\x61lready_started\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12\x1b\n\x0e\x66\x61ilure_reason\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x12\n\x10_already_startedB\x11\n\x0f_failure_reason\"$\n\x12XrayRestartRequest\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"\x80\x01\n\x13XrayRestartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x0bnot_started\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12\x1b\n\x0e\x66\x61ilure_reason\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_not_startedB\x11\n\x0f_failure_reason\"\x11\n\x0fXrayStopRequest\"\x12\n\x10XrayStopResponse\"\x19\n\x17XrayFetchVersionRequest\"+\n\x18XrayFetchVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\"\x11\n\x0fXrayLogsRequest\" \n\x10XrayLogsResponse\x12\x0c\n\x04line\x18\x01 \x01(\t2\xea\x02\n\x0bXrayService\x12>\n\tXrayStart\x12\x17.mnode.XrayStartRequest\x1a\x18.mnode.XrayStartResponse\x12\x44\n\x0bXrayRestart\x12\x19.mnode.XrayRestartRequest\x1a\x1a.mnode.XrayRestartResponse\x12;\n\x08XrayStop\x12\x16.mnode.XrayStopRequest\x1a\x17.mnode.XrayStopResponse\x12S\n\x10XrayFetchVersion\x12\x1e.mnode.XrayFetchVersionRequest\x1a\x1f.mnode.XrayFetchVersionResponse\x12\x43\n\x0eXrayLogsStream\x12\x16.mnode.XrayLogsRequest\x1a\x17.mnode.XrayLogsResponse0\x01\x62\x06proto3')



_XRAYSTARTREQUEST = DESCRIPTOR.message_types_by_name['XrayStartRequest']
_XRAYSTARTRESPONSE = DESCRIPTOR.message_types_by_name['XrayStartResponse']
_XRAYRESTARTREQUEST = DESCRIPTOR.message_types_by_name['XrayRestartRequest']
_XRAYRESTARTRESPONSE = DESCRIPTOR.message_types_by_name['XrayRestartResponse']
_XRAYSTOPREQUEST = DESCRIPTOR.message_types_by_name['XrayStopRequest']
_XRAYSTOPRESPONSE = DESCRIPTOR.message_types_by_name['XrayStopResponse']
_XRAYFETCHVERSIONREQUEST = DESCRIPTOR.message_types_by_name['XrayFetchVersionRequest']
_XRAYFETCHVERSIONRESPONSE = DESCRIPTOR.message_types_by_name['XrayFetchVersionResponse']
_XRAYLOGSREQUEST = DESCRIPTOR.message_types_by_name['XrayLogsRequest']
_XRAYLOGSRESPONSE = DESCRIPTOR.message_types_by_name['XrayLogsResponse']
XrayStartRequest = _reflection.GeneratedProtocolMessageType('XrayStartRequest', (_message.Message,), {
  'DESCRIPTOR' : _XRAYSTARTREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayStartRequest)
  })
_sym_db.RegisterMessage(XrayStartRequest)

XrayStartResponse = _reflection.GeneratedProtocolMessageType('XrayStartResponse', (_message.Message,), {
  'DESCRIPTOR' : _XRAYSTARTRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayStartResponse)
  })
_sym_db.RegisterMessage(XrayStartResponse)

XrayRestartRequest = _reflection.GeneratedProtocolMessageType('XrayRestartRequest', (_message.Message,), {
  'DESCRIPTOR' : _XRAYRESTARTREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayRestartRequest)
  })
_sym_db.RegisterMessage(XrayRestartRequest)

XrayRestartResponse = _reflection.GeneratedProtocolMessageType('XrayRestartResponse', (_message.Message,), {
  'DESCRIPTOR' : _XRAYRESTARTRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayRestartResponse)
  })
_sym_db.RegisterMessage(XrayRestartResponse)

XrayStopRequest = _reflection.GeneratedProtocolMessageType('XrayStopRequest', (_message.Message,), {
  'DESCRIPTOR' : _XRAYSTOPREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayStopRequest)
  })
_sym_db.RegisterMessage(XrayStopRequest)

XrayStopResponse = _reflection.GeneratedProtocolMessageType('XrayStopResponse', (_message.Message,), {
  'DESCRIPTOR' : _XRAYSTOPRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayStopResponse)
  })
_sym_db.RegisterMessage(XrayStopResponse)

XrayFetchVersionRequest = _reflection.GeneratedProtocolMessageType('XrayFetchVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _XRAYFETCHVERSIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayFetchVersionRequest)
  })
_sym_db.RegisterMessage(XrayFetchVersionRequest)

XrayFetchVersionResponse = _reflection.GeneratedProtocolMessageType('XrayFetchVersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _XRAYFETCHVERSIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayFetchVersionResponse)
  })
_sym_db.RegisterMessage(XrayFetchVersionResponse)

XrayLogsRequest = _reflection.GeneratedProtocolMessageType('XrayLogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _XRAYLOGSREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayLogsRequest)
  })
_sym_db.RegisterMessage(XrayLogsRequest)

XrayLogsResponse = _reflection.GeneratedProtocolMessageType('XrayLogsResponse', (_message.Message,), {
  'DESCRIPTOR' : _XRAYLOGSRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:mnode.XrayLogsResponse)
  })
_sym_db.RegisterMessage(XrayLogsResponse)

_XRAYSERVICE = DESCRIPTOR.services_by_name['XrayService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _XRAYSTARTREQUEST._serialized_start=24
  _XRAYSTARTREQUEST._serialized_end=58
  _XRAYSTARTRESPONSE._serialized_start=61
  _XRAYSTARTRESPONSE._serialized_end=195
  _XRAYRESTARTREQUEST._serialized_start=197
  _XRAYRESTARTREQUEST._serialized_end=233
  _XRAYRESTARTRESPONSE._serialized_start=236
  _XRAYRESTARTRESPONSE._serialized_end=364
  _XRAYSTOPREQUEST._serialized_start=366
  _XRAYSTOPREQUEST._serialized_end=383
  _XRAYSTOPRESPONSE._serialized_start=385
  _XRAYSTOPRESPONSE._serialized_end=403
  _XRAYFETCHVERSIONREQUEST._serialized_start=405
  _XRAYFETCHVERSIONREQUEST._serialized_end=430
  _XRAYFETCHVERSIONRESPONSE._serialized_start=432
  _XRAYFETCHVERSIONRESPONSE._serialized_end=475
  _XRAYLOGSREQUEST._serialized_start=477
  _XRAYLOGSREQUEST._serialized_end=494
  _XRAYLOGSRESPONSE._serialized_start=496
  _XRAYLOGSRESPONSE._serialized_end=528
  _XRAYSERVICE._serialized_start=531
  _XRAYSERVICE._serialized_end=893
# @@protoc_insertion_point(module_scope)
