# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: app/log/command/config.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import xray_api.proto.app.log.command.config_pb2


class LoggerServiceBase(abc.ABC):

    @abc.abstractmethod
    async def RestartLogger(self, stream: 'grpclib.server.Stream[app.log.command.config_pb2.RestartLoggerRequest, app.log.command.config_pb2.RestartLoggerResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/xray.app.log.command.LoggerService/RestartLogger': grpclib.const.Handler(
                self.RestartLogger,
                grpclib.const.Cardinality.UNARY_UNARY,
                xray_api.proto.app.log.command.config_pb2.RestartLoggerRequest,
                xray_api.proto.app.log.command.config_pb2.RestartLoggerResponse,
            ),
        }


class LoggerServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.RestartLogger = grpclib.client.UnaryUnaryMethod(
            channel,
            '/xray.app.log.command.LoggerService/RestartLogger',
            xray_api.proto.app.log.command.config_pb2.RestartLoggerRequest,
            xray_api.proto.app.log.command.config_pb2.RestartLoggerResponse,
        )
